// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6O3EHZrHDCT3023odlSiSD5IEowr80Fw',
    appId: '1:942596721103:web:336d5bb297285d62c7eaba',
    messagingSenderId: '942596721103',
    projectId: 'project-social-c1a90',
    authDomain: 'project-social-c1a90.firebaseapp.com',
    storageBucket: 'project-social-c1a90.appspot.com',
    measurementId: 'G-X83V4F0B8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0aCrAzLSXCCpngErkQ9eKSqtbLEoY2q8',
    appId: '1:942596721103:android:0e6f19fa049147b0c7eaba',
    messagingSenderId: '942596721103',
    projectId: 'project-social-c1a90',
    storageBucket: 'project-social-c1a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDebZGTcEsTfz0_MGPEzLH7vOy5NSDHWj8',
    appId: '1:942596721103:ios:cf6bde2592713d94c7eaba',
    messagingSenderId: '942596721103',
    projectId: 'project-social-c1a90',
    storageBucket: 'project-social-c1a90.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

}